#Systeams Config
#---------------
#The amount of steam 1mb of water makes.
#Note that making this bigger than the default value can cause augments to have a much lesser effect unless the amount of steam is equally.
#Range: 0.1 ~ 10.0
water_to_steam_ratio = 2.0
#The base amount of steam generated. Goes through some complicated maths and rounding before being turned into the actual steam value, so find what works with trial and error.
#Range: 10 ~ 400
base_steam_generation = 40
#Range: 0.1 ~ 10.0
steam_dynamo_output_multipler = 2.0

["Steam Values"]
	#The number of mb of steam produced per RF of energy usually produced by the same fuel in a dynamo
	#Range: 0.1 ~ 100.0
	stirling = 0.4
	#Range: 0.1 ~ 100.0
	magmatic = 0.4
	#Range: 0.1 ~ 100.0
	compression = 0.4
	#Range: 0.1 ~ 100.0
	numismatic = 0.4
	#Range: 0.1 ~ 100.0
	lapidary = 0.4
	#Range: 0.1 ~ 100.0
	disenchantment = 0.4
	#Range: 0.1 ~ 100.0
	gourmand = 0.4

