
#Recipe Settings
[recipes]
	#A mapping of sulfur source to origin block. The key is the sulfur source, the value is the block.
	#This is used by divination rod recipes to determine which (ore-)block to scan for, if e.g. a raw metal or ingot is used to craft the sulfur used in the rod.
	#Format is: ["source=block", "source=block", ...]
	sulfurSourceToBlockMapping = []

